// pages/teams/_id/developers/api-keys/index.vue
<template>
  <div>
    <h1 class="is-size-4" style="margin-bottom: 1rem">API keys</h1>
    <b-message
      v-if="hasUnrestrictedApiKey"
      type="is-warning"
      style="margin-top: 1rem"
      has-icon
    >
      You have one or more unrestricted API keys in your team. It's recommended
      to add scope, referrer, or IP address restrictions.
    </b-message>
    <b-table
      :loading="loading"
      :data="apiKeys.data"
      default-sort-direction="asc"
      sort-icon="arrow-up"
      sort-icon-size="is-small"
    >
      <template slot-scope="props">
        <b-table-column sortable field="name" label="Name">
          {{ props.row.name || "Unnamed API key" }}
          <b-tooltip
            v-if="
              !(
                props.row.ipRestrictions ||
                props.row.referrerRestrictions ||
                props.row.scopes
              )
            "
            label="Unrestricted"
          >
            <b-icon icon="alert" type="is-warning" />
          </b-tooltip>
        </b-table-column>
        <b-table-column sortable field="apiKey" label="API key">
          <code>{{ props.row.apiKey }}</code>
        </b-table-column>
        <b-table-column sortable field="createdAt" label="Added">{{
          new Date(props.row.createdAt).toLocaleDateString()
        }}</b-table-column>
        <b-table-column class="has-text-right">
          <b-tooltip label="Edit">
            <b-button
              tag="nuxt-link"
              :to="
                `/teams/${$route.params.id}/developers/api-keys/${props.row.id}`
              "
              type="is-primary"
              icon-right="pencil"
              outlined
            />
          </b-tooltip>
          <b-tooltip label="Delete">
            <b-button
              type="is-danger"
              icon-right="delete"
              outlined
              @click="
                deleteApiKey(props.row.id, props.row.name || 'Unnamed API key')
              "
            />
          </b-tooltip>
        </b-table-column>
      </template>
    </b-table>
    <h2 class="is-size-5" style="margin-top: 1rem">Create an API key</h2>
    <p>
      You'll be able to add restrictions such as scopes, referrers, IP
      addresses, and expiry after creating the API key.
    </p>
    <form @submit.prevent="add" style="margin: 0.5rem 0 1.5rem">
      <b-field label="Name">
        <b-input type="text" v-model="apiKeyName" />
      </b-field>
      <b-button type="is-primary" native-type="submit" :loading="loadingCreate"
        >Create API key</b-button
      >
    </form>
  </div>
</template>

<script lang="ts">
import { Vue, Component, Watch } from "vue-property-decorator";

@Component({
  middleware: "authenticated",
  layout: "teams"
})
export default class UsersApiKeys extends Vue {
  loading = false;
  loadingCreate = false;
  apiKeyName = "";
  apiKeys: any = { data: [] };

  async created() {
    return this.get();
  }

  async get() {
    this.loading = true;
    try {
      const { data } = await this.$axios.get(
        `/groups/${this.$route.params.id}/api-keys`
      );
      this.apiKeys = data;
    } catch (error) {}
    this.loading = false;
  }

  async add() {
    this.loadingCreate = true;
    try {
      const { data } = await this.$axios.put(
        `/groups/${this.$route.params.id}/api-keys`,
        {
          name: this.apiKeyName ? this.apiKeyName : undefined
        }
      );
      this.apiKeys.data.push(data.added);
    } catch (error) {}
    this.apiKeyName = "";
    this.loadingCreate = false;
  }

  async deleteApiKey(id: number, apiKey: string) {
    this.$buefy.dialog.confirm({
      title: "Deleting API key",
      message: `Are you sure you want to delete your API key <strong>${apiKey}</strong>? This action is not reversible, and this API key will stop working immediately.`,
      confirmText: "Yes, delete API key",
      cancelText: "No, don't delete",
      type: "is-danger",
      hasIcon: true,
      trapFocus: true,
      onConfirm: async () => {
        this.loading = true;
        try {
          await this.$axios.delete(
            `/groups/${this.$route.params.id}/api-keys/${id}`
          );
        } catch (error) {}
        return this.get();
      }
    });
  }

  get hasUnrestrictedApiKey() {
    return !!this.apiKeys.data.find(
      (i: any) => !(i.ipRestrictions || i.referrerRestrictions || i.scopes)
    );
  }
}
</script>

// src/routes/groups/[id]/api-keys/index.svelte
<script lang="ts">
  import { stores } from "@sapper/app";
  import {
    Button,
    DataTable,
    DataTableSkeleton,
    Form,
    FormGroup,
    InlineLoading,
    InlineNotification,
    Modal,
    TextInput,
  } from "carbon-components-svelte";
  import SubtractAlt20 from "carbon-icons-svelte/lib/SubtractAlt20";
  import Edit20 from "carbon-icons-svelte/lib/Edit20";
  import { onMount } from "svelte";
  import { api } from "../../../../helpers/api";
  import { can } from "../../../../helpers/auth-token";

  const { page } = stores();
  const { id } = $page.params;

  let apiKeys: any[] = [];
  let loading = true;
  let state = "ready";
  let newApiKey = "";
  let errorMessage = "";
  let openDelete = false;
  let deleteApiKey: number | null = null;
  onMount(async () => {
    apiKeys = await api("GET", `/groups/${id}/api-keys`);
    loading = false;
  });

  const add = async () => {
    state = "adding";
    try {
      apiKeys.push(
        await api("POST", `/groups/${id}/api-keys`, {
          name: newApiKey,
        })
      );
      newApiKey = "";
      state = "added";
      setTimeout(() => (state = "ready"), 5000);
    } catch (error) {
      errorMessage = error.message;
      state = "ready";
    }
  };

  const remove = async () => {
    state = "removing";
    openDelete = false;
    try {
      await api("DELETE", `/groups/${id}/api-keys/${deleteApiKey}`);
      apiKeys = apiKeys.filter((i) => i.id !== deleteApiKey);
      state = "removed";
      setTimeout(() => (state = "ready"), 5000);
    } catch (error) {
      errorMessage = error.message;
      state = "ready";
    }
    deleteApiKey = null;
  };
</script>

<h1>API keys</h1>

<Modal
  bind:open={openDelete}
  danger
  modalHeading="Delete API key"
  primaryButtonText="Delete"
  secondaryButtonText="Cancel"
  on:click:button--secondary={() => (openDelete = false)}
  on:submit={() => remove()}>
  <p>
    Are you sure you want to delete this API key? This action is not reversible,
    and your API key will stop working instantly.
  </p>
</Modal>

{#if loading}
  <DataTableSkeleton showHeader={false} showToolbar={false} />
{:else if apiKeys}
  <DataTable
    sortable
    headers={[{ key: 'name', value: 'Name' }, { key: 'apiKey', value: 'API key' }, { key: 'scopes', value: 'Scopes' }, { key: 'createdAt', value: 'Created' }, { key: 'actions', value: '' }]}
    rows={apiKeys}>
    <span slot="cell-header" let:header>
      {#if header.key === 'port'}
        {header.value}
        (network)
      {:else}{header.value}{/if}
    </span>
    <span slot="cell" let:row let:cell>
      {#if cell.key === 'apiKeyId'}
        {row.apiKey.name}
      {:else if cell.key === 'createdAt'}
        {new Date(cell.value).toLocaleDateString()}
      {:else if cell.key === 'scopes'}
        {cell.value.length || 'None'}
      {:else if cell.key === 'apiKey'}
        <code>{cell.value}</code>
      {:else if cell.key === 'actions'}
        <div class="align-right">
          {#if can(`group-${id}:api-key-${row.id}-delete`)}
            <Button
              icon={Edit20}
              href="/groups/{id}/api-keys/{row.id}"
              hasIconOnly
              tooltipPosition="bottom"
              tooltipAlignment="center"
              iconDescription="Edit" />
          {/if}
          {#if can(`group-${id}:api-key-${row.id}-delete`)}
            <Button
              icon={SubtractAlt20}
              on:click={() => {
                openDelete = true;
                deleteApiKey = row.id;
              }}
              hasIconOnly
              kind="danger"
              tooltipPosition="bottom"
              tooltipAlignment="center"
              iconDescription="Delete" />
          {/if}
        </div>
      {:else}{cell.value}{/if}
    </span>
  </DataTable>
  {#if state === 'removing'}
    <InlineLoading status="active" description="Deleting..." />
  {:else if state === 'removed'}
    <InlineLoading status="finished" description="Deleted" />
  {/if}
  <h2>Create a API key</h2>
  {#if errorMessage}
    <InlineNotification kind="error" title={errorMessage} />
  {/if}
  <Form on:submit={add}>
    <FormGroup>
      <TextInput labelText="Name" bind:value={newApiKey} required />
    </FormGroup>
    <Button type="submit">Create API key</Button>
  </Form>
  {#if state === 'adding'}
    <InlineLoading status="active" description="Creating..." />
  {:else if state === 'added'}
    <InlineLoading status="finished" description="Created" />
  {/if}
{/if}
