// src/routes/groups/[id]/billing/index.svelte
<script lang="ts">
  import { stores } from "@sapper/app";
  import {
    Button,
    Form,
    FormGroup,
    InlineLoading,
    TextInput,
    Grid,
    Row,
    Column,
    InlineNotification,
  } from "carbon-components-svelte";
  import { onMount } from "svelte";
  import { api } from "../../../../helpers/api";

  const { page } = stores();
  const { id } = $page.params;

  let group: any = {
    email: "",
    name: "",
    phone: "",
    address: {
      line1: "",
      line2: "",
      city: "",
      state: "",
      postal_code: "",
      country: "",
    },
  };
  let loading = true;
  let state = "ready";
  let customerNotFound = false;
  let errorMessage = "";
  onMount(async () => {
    try {
      group = await api("GET", `/groups/${id}/billing`);
    } catch (error) {
      if (error.message.includes("404010")) customerNotFound = true;
    }
    loading = false;
  });

  const save = async () => {
    state = "saving";
    try {
      group = await api(
        customerNotFound ? "POST" : "PATCH",
        `/groups/${id}/billing`,
        {
          email: group.email,
          name: group.name,
          phone: group.phone,
          address: group.address,
        }
      );
      state = "saved";
      customerNotFound = false;
      setTimeout(() => (state = "ready"), 5000);
    } catch (err) {
      errorMessage = err.message;
      state = "ready";
    }
  };
</script>

<h1>Billing</h1>

{#if errorMessage}
  <InlineNotification kind="error" title={errorMessage} />
{/if}

{#if loading}
  <InlineLoading description="Loading group..." />
{:else}
  {#if customerNotFound}
    <InlineLoading
      status="error"
      description="Your account is not activated for billing yet. Fill the form below to setup a billing account." />
  {/if}
  <Form on:submit={save}>
    <FormGroup>
      <TextInput labelText="Name" bind:value={group.name} required />
    </FormGroup>
    <FormGroup>
      <TextInput labelText="Billing email" bind:value={group.email} required />
    </FormGroup>
    <FormGroup>
      <TextInput type="tel" labelText="Phone" bind:value={group.phone} />
    </FormGroup>
    <FormGroup legendText="Address">
      <Row>
        <Column>
          <TextInput
            labelText="Street address"
            bind:value={group.address.line1} />
        </Column>
        <Column>
          <TextInput
            labelText="Apartment, suite, etc."
            bind:value={group.address.line2} />
        </Column>
      </Row>
      <Row>
        <Column>
          <TextInput labelText="City" bind:value={group.address.city} />
        </Column>
        <Column>
          <TextInput labelText="State" bind:value={group.address.state} />
        </Column>
      </Row>
      <Row>
        <Column>
          <TextInput
            labelText="Postal code"
            bind:value={group.address.postal_code} />
        </Column>
        <Column>
          <TextInput labelText="Country" bind:value={group.address.country} />
        </Column>
      </Row>
    </FormGroup>
    <Button type="submit">
      {#if customerNotFound}
        Setup billing account
      {:else}Save billing account{/if}
    </Button>
  </Form>
  {#if state === 'saving'}
    <InlineLoading status="active" description="Saving..." />
  {:else if state === 'saved'}
    <InlineLoading status="finished" description="Success" />
  {/if}
{/if}

// pages/teams/_username/billing/index.vue
<template>
  <div>
    <h1 class="is-size-4">Customer details</h1>
    <form @submit.prevent="save" style="margin-top: 1rem">
      <b-field label="Name">
        <b-input type="text" v-model="customer.name" required />
      </b-field>
      <div class="columns">
        <b-field
          label="Email"
          class="column"
          style="margin-bottom: 0; padding-bottom: 0"
        >
          <b-input type="email" v-model="customer.email" required />
        </b-field>
        <b-field
          label="Phone"
          class="column"
          style="margin-bottom: 0; padding-bottom: 0"
        >
          <b-input type="text" v-model="customer.phone" />
        </b-field>
      </div>
      <b-field label="Address">
        <b-input type="text" v-model="customer.address.line1" />
      </b-field>
      <div class="columns">
        <b-field
          label="Postal code"
          class="column"
          style="margin-bottom: 0; padding-bottom: 0"
        >
          <b-input type="text" v-model="customer.address.postal_code" />
        </b-field>
        <b-field
          label="City"
          class="column"
          style="margin-bottom: 0; padding-bottom: 0"
        >
          <b-input type="text" v-model="customer.address.city" />
        </b-field>
      </div>
      <div class="columns">
        <b-field
          label="State"
          class="column"
          style="margin-bottom: 0; padding-bottom: 0"
        >
          <b-input type="text" v-model="customer.address.state" />
        </b-field>
        <b-field
          label="Country"
          class="column"
          style="margin-bottom: 0; padding-bottom: 0"
        >
          <b-input type="text" v-model="customer.address.country" />
        </b-field>
      </div>
      <b-button type="is-primary" native-type="submit" :loading="loadingSave">
        Update details
      </b-button>
      <b-loading :is-full-page="false" :active.sync="loading"></b-loading>
    </form>
  </div>
</template>

<script lang="ts">
import { Vue, Component, Watch } from "vue-property-decorator";

@Component({
  middleware: "authenticated",
  layout: "teams",
})
export default class BillingDetails extends Vue {
  customer = {
    email: "",
    name: "",
    phone: "",
    address: {
      city: "",
      country: "",
      line1: "",
      line2: "",
      postal_code: "",
      state: "",
    },
  };
  loading = false;
  loadingSave = false;

  async mounted() {
    return this.get();
  }

  async get() {
    this.loading = true;
    try {
      const { data } = await this.$axios.get(
        `/organizations/${this.$route.params.username}/billing`
      );
      if (!data.address)
        data.address = {
          city: "",
          country: "",
          line1: "",
          line2: "",
          postal_code: "",
          state: "",
        };
      this.customer = data;
    } catch (error) {}
    this.loading = false;
  }

  async save() {
    this.loadingSave = true;
    try {
      const { data } = await this.$axios.patch(
        `/organizations/${this.$route.params.username}/billing`,
        {
          name: this.customer.name,
          email: this.customer.email,
          phone: this.customer.phone,
          address: this.customer.address,
        }
      );
    } catch (error) {}
    this.loadingSave = false;
  }
}
</script>
