// pages/teams/_username/developers/webhooks/index.vue
<template>
  <div>
    <h1 class="is-size-4" style="margin-bottom: 1rem">Webhooks</h1>
    <b-table
      :loading="loading"
      :data="webhooks.data"
      default-sort-direction="asc"
      sort-icon="arrow-up"
      sort-icon-size="is-small"
    >
      <template slot-scope="props">
        <b-table-column sortable field="url" label="URL">
          <span>{{ truncate(props.row.url) }}</span>
          <b-tooltip v-if="props.row.isActive" label="Active">
            <b-icon icon="calendar-check" type="is-success" />
          </b-tooltip>
          <b-tooltip v-else label="Inactive">
            <b-icon icon="calendar-remove" type="is-danger" />
          </b-tooltip>
        </b-table-column>
        <b-table-column
          sortable
          field="createdAt"
          label="Event"
        >{{ webhooksData[props.row.event] || props.row.event }}</b-table-column>
        <b-table-column class="has-text-right">
          <b-tooltip label="Edit">
            <b-button
              tag="nuxt-link"
              :to="
                `/teams/${$route.params.id}/developers/webhooks/${props.row.id}`
              "
              type="is-primary"
              icon-right="pencil"
              outlined
            />
          </b-tooltip>
          <b-tooltip label="Delete">
            <b-button
              type="is-danger"
              icon-right="delete"
              outlined
              @click="
                deleteWebhook(
                  props.row.id,
                  webhooksData[props.row.event] || props.row.event
                )
              "
            />
          </b-tooltip>
        </b-table-column>
      </template>
    </b-table>
    <h2 class="is-size-5" style="margin-top: 1rem">Create a webhook</h2>
    <p>
      You'll be able to add event restrictions and a secret key after creating
      the webhook.
    </p>
    <form @submit.prevent="add" style="margin: 0.5rem 0 1.5rem">
      <div class="columns">
        <div class="column">
          <b-field label="URL">
            <b-input type="url" v-model="webhookUrl" required />
          </b-field>
        </div>
        <div class="column">
          <b-field label="Event">
            <b-select placeholder="Select an event" v-model="webhookEvent" expanded required>
              <option
                v-for="(name, value) in webhooksData"
                :value="value"
                :key="`t${value}${name}`"
              >{{ name }}</option>
            </b-select>
          </b-field>
        </div>
      </div>
      <b-button type="is-primary" native-type="submit" :loading="loadingCreate">Create webhook</b-button>
    </form>
  </div>
</template>

<script lang="ts">
import { Vue, Component, Watch } from "vue-property-decorator";
import webhooksData from "../../../../../data/webhooks.json";
import { truncate } from "../../../../../util/string";

@Component({
  middleware: "authenticated",
  layout: "teams",
})
export default class UsersWebhooks extends Vue {
  loading = false;
  loadingCreate = false;
  webhookUrl = "";
  webhookEvent = "*";
  webhooksData: any = webhooksData;
  webhooks: any = { data: [] };
  truncate = truncate;

  async created() {
    return this.get();
  }

  async get() {
    this.loading = true;
    try {
      const { data } = await this.$axios.get(
        `/organizations/${this.$route.params.id}/webhooks`
      );
      this.webhooks = data;
    } catch (error) {}
    this.loading = false;
  }

  async add() {
    this.loadingCreate = true;
    try {
      const { data } = await this.$axios.put(
        `/organizations/${this.$route.params.id}/webhooks`,
        {
          url: this.webhookUrl,
          event: this.webhookEvent,
        }
      );
      this.webhooks.data.push(data.added);
    } catch (error) {}
    this.webhookUrl = "";
    this.webhookEvent = "*";
    this.loadingCreate = false;
  }

  async deleteWebhook(id: number, webhook: string) {
    this.$buefy.dialog.confirm({
      title: "Deleting webhook",
      message: `Are you sure you want to delete your webhook for <strong>${webhook}</strong>? This action is not reversible, and this webhook will stop triggering immediately.`,
      confirmText: "Yes, delete webhook",
      cancelText: "No, don't delete",
      type: "is-danger",
      hasIcon: true,
      trapFocus: true,
      onConfirm: async () => {
        this.loading = true;
        try {
          await this.$axios.delete(
            `/organizations/${this.$route.params.id}/webhooks/${id}`
          );
        } catch (error) {}
        return this.get();
      },
    });
  }
}
</script>

// src/routes/groups/[id]/webhooks/index.svelte
<script lang="ts">
  import { stores } from "@sapper/app";
  import {
    Button,
    DataTable,
    DataTableSkeleton,
    Form,
    FormGroup,
    Icon,
    InlineLoading,
    InlineNotification,
    Modal,
    TextInput,
    TooltipIcon,
  } from "carbon-components-svelte";
  import CheckmarkFilled20 from "carbon-icons-svelte/lib/CheckmarkFilled20";
  import Warning20 from "carbon-icons-svelte/lib/Warning20";
  import SubtractAlt20 from "carbon-icons-svelte/lib/SubtractAlt20";
  import Edit20 from "carbon-icons-svelte/lib/Edit20";
  import { onMount } from "svelte";
  import { api } from "../../../../helpers/api";
  import { can } from "../../../../helpers/auth-token";

  const { page } = stores();
  const { id } = $page.params;

  let webhooks: any[] = [];
  let loading = true;
  let state = "ready";
  let newWebhook = "";
  let errorMessage = "";
  let openDelete = false;
  let deleteWebhook: number | null = null;
  onMount(async () => {
    webhooks = await api("GET", `/groups/${id}/webhooks`);
    loading = false;
  });

  const add = async () => {
    state = "adding";
    try {
      webhooks.push(
        await api("POST", `/groups/${id}/webhooks`, {
          url: newWebhook,
          event: "create-webhook",
        })
      );
      newWebhook = "";
      state = "added";
      setTimeout(() => (state = "ready"), 5000);
    } catch (error) {
      errorMessage = error.message;
      state = "ready";
    }
  };

  const remove = async () => {
    state = "removing";
    openDelete = false;
    try {
      await api("DELETE", `/groups/${id}/webhooks/${deleteWebhook}`);
      webhooks = webhooks.filter((i) => i.id !== deleteWebhook);
      state = "removed";
      setTimeout(() => (state = "ready"), 5000);
    } catch (error) {
      errorMessage = error.message;
      state = "ready";
    }
    deleteWebhook = null;
  };
</script>

<h1>Webhooks</h1>

<Modal
  bind:open={openDelete}
  danger
  modalHeading="Delete webhook"
  primaryButtonText="Delete"
  secondaryButtonText="Cancel"
  on:click:button--secondary={() => (openDelete = false)}
  on:submit={() => remove()}>
  <p>
    Are you sure you want to delete this webhook? This action is not reversible,
    and your webhook will stop triggering instantly.
  </p>
</Modal>

{#if loading}
  <DataTableSkeleton showHeader={false} showToolbar={false} />
{:else if webhooks}
  <DataTable
    sortable
    headers={[{ key: 'event', value: 'Event' }, { key: 'url', value: 'URL' }, { key: 'createdAt', value: 'Created' }, { key: 'actions', value: '' }]}
    rows={webhooks}>
    <span slot="cell-header" let:header>
      {#if header.key === 'port'}
        {header.value}
        (network)
      {:else}{header.value}{/if}
    </span>
    <span slot="cell" let:row let:cell>
      {#if cell.key === 'createdAt'}
        {new Date(cell.value).toLocaleDateString()}
      {:else if cell.key === 'url'}
        <code>{cell.value.substr(0, 20)}</code>
        {#if row.isActive}
          <span class="middle-icon">
            <TooltipIcon tooltipText="Active">
              <Icon render={CheckmarkFilled20} />
            </TooltipIcon>
          </span>
        {:else}
          <span class="middle-icon">
            <TooltipIcon tooltipText="Inactive">
              <Icon render={Warning20} />
            </TooltipIcon>
          </span>
        {/if}
      {:else if cell.key === 'actions'}
        <div class="align-right">
          {#if can(`group-${id}:webhook-${row.id}-delete`)}
            <Button
              icon={Edit20}
              href="/groups/{id}/webhooks/{row.id}"
              hasIconOnly
              tooltipPosition="bottom"
              tooltipAlignment="center"
              iconDescription="Edit" />
          {/if}
          {#if can(`group-${id}:webhook-${row.id}-delete`)}
            <Button
              icon={SubtractAlt20}
              on:click={() => {
                openDelete = true;
                deleteWebhook = row.id;
              }}
              hasIconOnly
              kind="danger"
              tooltipPosition="bottom"
              tooltipAlignment="center"
              iconDescription="Delete" />
          {/if}
        </div>
      {:else}{cell.value}{/if}
    </span>
  </DataTable>
  {#if state === 'removing'}
    <InlineLoading status="active" description="Deleting..." />
  {:else if state === 'removed'}
    <InlineLoading status="finished" description="Deleted" />
  {/if}
  <h2>Create a webhook</h2>
  {#if errorMessage}
    <InlineNotification kind="error" title={errorMessage} />
  {/if}
  <Form on:submit={add}>
    <FormGroup>
      <TextInput type="url" labelText="URL" bind:value={newWebhook} required />
    </FormGroup>
    <Button type="submit">Create webhook</Button>
  </Form>
  {#if state === 'adding'}
    <InlineLoading status="active" description="Creating..." />
  {:else if state === 'added'}
    <InlineLoading status="finished" description="Created" />
  {/if}
{/if}
