// src/routes/users/[id]/emails.svelte
<script lang="ts">
  import { stores } from "@sapper/app";
  import {
    Button,
    DataTable,
    DataTableSkeleton,
    Form,
    FormGroup,
    Icon,
    InlineLoading,
    InlineNotification,
    RadioButton,
    RadioButtonGroup,
    Select,
    SelectItem,
    TextInput,
    TooltipIcon,
    Modal,
  } from "carbon-components-svelte";
  import CheckmarkFilled20 from "carbon-icons-svelte/lib/CheckmarkFilled20";
  import WarningAltFilled20 from "carbon-icons-svelte/lib/WarningAltFilled20";
  import SubtractAlt20 from "carbon-icons-svelte/lib/SubtractAlt20";
  import { onMount } from "svelte";
  import { api } from "../../../helpers/api";
  import { can } from "../../../helpers/auth-token";

  const { page } = stores();
  const { id } = $page.params;

  let profile: any = null;
  let emails: any[] = [];
  let loading = true;
  let state = "ready";
  let newEmail = "";
  let errorMessage = "";
  let openDelete = false;
  let deleteEmail: number | null = null;
  onMount(async () => {
    profile = await api("GET", `/users/${id}`);
    emails = await api("GET", `/users/${id}/emails`);
    loading = false;
  });

  const save = async () => {
    state = "saving";
    profile = await api("PATCH", `/users/${id}`, {
      prefersEmailId: profile.prefersEmailId,
      notificationEmails: profile.notificationEmails,
    });
    state = "saved";
    setTimeout(() => (state = "ready"), 5000);
  };

  const add = async () => {
    state = "adding";
    try {
      emails.push(
        await api("POST", `/users/${id}/emails`, {
          email: newEmail,
        })
      );
      newEmail = "";
      state = "added";
      setTimeout(() => (state = "ready"), 5000);
    } catch (error) {
      errorMessage = error.message;
      state = "ready";
    }
  };

  const remove = async () => {
    state = "removing";
    openDelete = false;
    try {
      await api("DELETE", `/users/${id}/emails/${deleteEmail}`);
      emails = emails.filter((i) => i.id !== deleteEmail);
      if (profile.prefersEmailId === deleteEmail)
        profile = await api("GET", `/users/${id}`);
      state = "removed";
      setTimeout(() => (state = "ready"), 5000);
    } catch (error) {
      errorMessage = error.message;
      state = "ready";
    }
    deleteEmail = null;
  };
</script>

<h1>Emails</h1>

<Modal
  bind:open={openDelete}
  danger
  modalHeading="Delete email"
  primaryButtonText="Delete"
  secondaryButtonText="Cancel"
  on:click:button--secondary={() => (openDelete = false)}
  on:submit={() => remove()}>
  <p>Are you sure you want to delete this email?</p>
</Modal>

{#if errorMessage}
  <InlineNotification kind="error" title={errorMessage} />
{/if}

{#if loading}
  <DataTableSkeleton showHeader={false} showToolbar={false} />
{:else if emails && profile}
  <DataTable
    sortable
    headers={[{ key: 'email', value: 'Email address' }, { key: 'createdAt', value: 'Added' }, { key: 'actions', value: '' }]}
    rows={emails}>
    <span slot="cell-header" let:header>
      {#if header.key === 'port'}
        {header.value}
        (network)
      {:else}{header.value}{/if}
    </span>
    <span slot="cell" let:row let:cell>
      {#if cell.key === 'email'}
        {row.email}
        {#if row.isVerified}
          <span class="middle-icon">
            <TooltipIcon tooltipText="Verified">
              <Icon render={CheckmarkFilled20} />
            </TooltipIcon>
          </span>
        {:else}
          <span class="middle-icon">
            <TooltipIcon tooltipText="Not verified">
              <Icon render={WarningAltFilled20} />
            </TooltipIcon>
          </span>
        {/if}
      {:else if cell.key === 'createdAt'}
        {new Date(cell.value).toLocaleDateString()}
      {:else if cell.key === 'actions'}
        <div class="align-right">
          {#if can(`user-${id}:email-${row.id}-delete`)}
            <Button
              icon={SubtractAlt20}
              on:click={() => {
                openDelete = true;
                deleteEmail = row.id;
              }}
              hasIconOnly
              kind="danger"
              tooltipPosition="bottom"
              tooltipAlignment="center"
              iconDescription="Delete" />
          {/if}
        </div>
      {:else}{cell.value}{/if}
    </span>
  </DataTable>
  {#if state === 'removing'}
    <InlineLoading status="active" description="Deleting..." />
  {:else if state === 'removed'}
    <InlineLoading status="finished" description="Deleted" />
  {/if}
  <h2>Add email</h2>
  <Form on:submit={add}>
    <FormGroup>
      <TextInput
        type="email"
        labelText="Email address"
        bind:value={newEmail}
        required />
    </FormGroup>
    <Button type="submit">Add email</Button>
  </Form>
  {#if state === 'adding'}
    <InlineLoading status="active" description="Adding..." />
  {:else if state === 'added'}
    <InlineLoading status="finished" description="Added" />
  {/if}
  <h2>Settings</h2>
  <Form on:submit={save}>
    <FormGroup>
      <Select labelText="Primary email" bind:selected={profile.prefersEmailId}>
        {#each emails as email}
          <SelectItem value={String(email.id)} text={email.email} />
        {/each}
      </Select>
    </FormGroup>
    <FormGroup legendText="Email notifications">
      <RadioButtonGroup bind:selected={profile.notificationEmails}>
        <RadioButton value="ACCOUNT" labelText="Account-related emails" />
        <RadioButton value="PROMOTIONS" labelText="Promotions" />
      </RadioButtonGroup>
    </FormGroup>
    <Button type="submit">Update email settings</Button>
  </Form>
  {#if state === 'saving'}
    <InlineLoading status="active" description="Saving..." />
  {:else if state === 'saved'}
    <InlineLoading status="finished" description="Success" />
  {/if}
{/if}

// pages/users/_id/emails.vue
<template>
  <div>
    <h1 class="is-size-4 mb-4">Emails</h1>
    <b-table
      :loading="loading"
      :data="emails.data"
      default-sort-direction="asc"
      sort-icon="arrow-up"
      sort-icon-size="is-small"
    >
      <template slot-scope="props" v-if="props.row">
        <b-table-column sortable field="email" label="Email">
          {{ props.row.email }}
          <b-tooltip v-if="props.row.isVerified" label="Verified">
            <b-icon icon="check-circle" type="is-success" />
          </b-tooltip>
          <b-tooltip v-else label="Unverified">
            <b-icon icon="alert" type="is-warning" />
          </b-tooltip>
        </b-table-column>
        <b-table-column sortable field="createdAt" label="Added">{{
          new Date(props.row.createdAt).toLocaleDateString()
        }}</b-table-column>
        <b-table-column class="has-text-right">
          <b-tooltip label="Delete">
            <b-button
              type="is-danger"
              icon-right="delete"
              @click="deleteEmail(props.row.id, props.row.email)"
            />
          </b-tooltip>
        </b-table-column>
      </template>
    </b-table>
    <div class="has-text-centered">
      <b-button
        v-if="emails.hasMore"
        @click="get"
        icon-right="arrow-down"
        :loading="loading"
        >Load more emails</b-button
      >
    </div>
    <h2 class="is-size-5 mb-3">Add email</h2>
    <form @submit.prevent="add">
      <b-field label="Email">
        <b-input type="email" v-model="newEmail" required />
      </b-field>
      <b-button type="is-primary" native-type="submit" :loading="loadingAdd"
        >Add email</b-button
      >
    </form>
    <h2 class="is-size-5 mb-3">Email preferences</h2>
    <form @submit.prevent="save">
      <b-field
        label="Primary email"
        message="We'll send you emails only on your primary email"
      >
        <b-select v-model="prefersEmailId" expanded>
          <option
            v-for="(email, i) in emails.data"
            :key="`e${email.id}${i}`"
            :value="email.id"
          >
            {{ email.email }}
          </option>
        </b-select>
      </b-field>
      <b-field label="Notification emails">
        <div>
          <b-radio
            name="radioNotificationEmails"
            native-value="ACCOUNT"
            v-model="notificationEmails"
            >Account and security</b-radio
          >
          <b-radio
            name="radioNotificationEmails"
            native-value="UPDATES"
            v-model="notificationEmails"
            >App updates</b-radio
          >
          <b-radio
            name="radioNotificationEmails"
            native-value="PROMOTIONS"
            v-model="notificationEmails"
            >Promotions</b-radio
          >
        </div>
      </b-field>
      <b-button type="is-primary" native-type="submit" :loading="loadingSave"
        >Update settings</b-button
      >
    </form>
  </div>
</template>

<script lang="ts">
import { Vue, Component, Watch } from "vue-property-decorator";

@Component({
  middleware: "authenticated",
  layout: "users"
})
export default class UsersEmails extends Vue {
  newEmail = "";
  loading = false;
  loadingAdd = false;
  loadingSave = false;
  prefersEmailId = 0;
  notificationEmails = "ACCOUNT";
  emails: any = { data: [] };

  async created() {
    return this.get();
  }

  async get() {
    this.loading = true;
    try {
      const { data } = await this.$axios.get(
        `/users/${this.$route.params.id}/emails?take=10${
          this.emails.data.length
            ? `&after=${this.emails.data[this.emails.data.length - 1].id}`
            : ""
        }`
      );
      this.emails.data.push(...(data.data || []));
      this.emails.hasMore = data.hasMore;
      this.emails = data;
    } catch (error) {}
    try {
      const user = await this.$axios.get(`/users/${this.$route.params.id}`);
      this.notificationEmails = user.data.notificationEmails;
      this.prefersEmailId = user.data.prefersEmailId;
    } catch (error) {}
    this.loading = false;
  }

  async add() {
    this.loadingAdd = true;
    try {
      const { data } = await this.$axios.put(
        `/users/${this.$route.params.id}/emails`,
        {
          email: this.newEmail
        }
      );
      this.emails.data.push(data.added);
      this.newEmail = "";
    } catch (error) {}
    this.loadingAdd = false;
  }

  async save() {
    this.loadingSave = true;
    try {
      await this.$axios.patch(`/users/${this.$route.params.id}`, {
        primaryEmail: this.prefersEmailId,
        notificationEmails: this.notificationEmails
      });
    } catch (error) {}
    this.loadingSave = false;
  }

  async deleteEmail(id: number, email: string) {
    this.$buefy.dialog.confirm({
      title: "Deleting email",
      message: `Are you sure you want to delete your email <strong>${email}</strong>? This action is not reversible, and you'll have to verify this email again if you change your mind.`,
      confirmText: "Yes, delete email",
      cancelText: "No, don't delete",
      type: "is-danger",
      hasIcon: true,
      trapFocus: true,
      onConfirm: async () => {
        this.loading = true;
        try {
          await this.$axios.delete(
            `/users/${this.$route.params.id}/emails/${id}`
          );
        } catch (error) {}
        return this.get();
      }
    });
  }
}
</script>
